const pizzas = [
  {
    name: "Margherita",
    description: "Classic delight with 100% real mozzarella cheese.",
    image: "../assets/pizza1.jpg",
    price: 10.99,
    dateOfLaunch: "2023-01-15",
    category: "Vegetarian",
    freeDelivery: true,
  },
  {
    name: "Pepperoni",
    description: "Loaded with pepperoni and cheese for a spicy kick.",
    image: "../assets/pizza2.jpg",
    price: 12.99,
    dateOfLaunch: "2023-02-10",
    category: "Non-Vegetarian",
    freeDelivery: false,
  },
  {
    name: "Veggie",
    description: "A garden-fresh mix of peppers, onions, and olives.",
    image: "../assets/pizza3.jpg",
    price: 11.99,
    dateOfLaunch: "2023-03-05",
    category: "Vegetarian",
    freeDelivery: true,
  },
  {
    name: "BBQ Chicken",
    description: "Tangy BBQ sauce, grilled chicken, and red onions.",
    image: "../assets/pizza4.jpg",
    price: 13.99,
    dateOfLaunch: "2023-04-20",
    category: "Non-Vegetarian",
    freeDelivery: false,
  },
  {
    name: "Hawaiian",
    description: "A tropical mix of ham, pineapple, and cheese.",
    image: "../assets/pizza5.jpg",
    price: 12.49,
    dateOfLaunch: "2023-05-10",
    category: "Non-Vegetarian",
    freeDelivery: true,
  },
  {
    name: "Four Cheese",
    description: "Mozzarella, cheddar, parmesan, and blue cheese.",
    image: "../assets/pizza6.jpg",
    price: 13.49,
    dateOfLaunch: "2023-06-01",
    category: "Vegetarian",
    freeDelivery: false,
  },
  {
    name: "Meat Lovers",
    description: "Pepperoni, sausage, ham, bacon, and beef.",
    image: "../assets/pizza7.jpg",
    price: 15.99,
    dateOfLaunch: "2023-06-20",
    category: "Non-Vegetarian",
    freeDelivery: true,
  },
  {
    name: "Spinach Alfredo",
    description: "Creamy Alfredo sauce, spinach, and mozzarella.",
    image: "../assets/pizza8.jpg",
    price: 12.29,
    dateOfLaunch: "2023-07-05",
    category: "Vegetarian",
    freeDelivery: false,
  },
  {
    name: "Buffalo Chicken",
    description: "Spicy buffalo sauce, chicken, and red onions.",
    image: "../assets/pizza9.jpg",
    price: 14.49,
    dateOfLaunch: "2023-07-18",
    category: "Non-Vegetarian",
    freeDelivery: true,
  },
  {
    name: "Mushroom Feast",
    description: "Loaded with mushrooms, cheese, and herbs.",
    image: "../assets/pizza10.jpg",
    price: 11.49,
    dateOfLaunch: "2023-08-01",
    category: "Vegetarian",
    freeDelivery: true,
  },
  {
    name: "Tandoori Paneer",
    description: "Indian-style paneer, peppers, and tandoori spices.",
    image: "../assets/pizza1.jpg",
    price: 13.29,
    dateOfLaunch: "2023-08-15",
    category: "Vegetarian",
    freeDelivery: false,
  },
  {
    name: "Sausage & Peppers",
    description: "Italian sausage, bell peppers, and onions.",
    image: "../assets/pizza2.jpg",
    price: 13.99,
    dateOfLaunch: "2023-09-01",
    category: "Non-Vegetarian",
    freeDelivery: true,
  },
  {
    name: "Pesto Veggie",
    description: "Pesto sauce, zucchini, tomatoes, and feta.",
    image: "../assets/pizza3.jpg",
    price: 12.79,
    dateOfLaunch: "2023-09-15",
    category: "Vegetarian",
    freeDelivery: false,
  },
  {
    name: "Mexican Fiesta",
    description: "Spicy chicken, jalapeños, and corn.",
    image: "../assets/pizza4.jpg",
    price: 14.29,
    dateOfLaunch: "2023-10-01",
    category: "Non-Vegetarian",
    freeDelivery: true,
  },
  {
    name: "Truffle Mushroom",
    description: "Truffle oil, mushrooms, and mozzarella.",
    image: "../assets/pizza5.jpg",
    price: 15.49,
    dateOfLaunch: "2023-10-15",
    category: "Vegetarian",
    freeDelivery: false,
  },
  {
    name: "Chicken Supreme",
    description: "Chicken, peppers, onions, and olives.",
    image: "../assets/pizza6.jpg",
    price: 14.99,
    dateOfLaunch: "2023-11-01",
    category: "Non-Vegetarian",
    freeDelivery: true,
  },
  {
    name: "Paneer Tikka",
    description: "Paneer cubes, tikka sauce, and onions.",
    image: "../assets/pizza7.jpg",
    price: 13.49,
    dateOfLaunch: "2023-11-15",
    category: "Vegetarian",
    freeDelivery: true,
  },
  {
    name: "Seafood Special",
    description: "Shrimp, calamari, and garlic sauce.",
    image: "../assets/pizza8.jpg",
    price: 16.99,
    dateOfLaunch: "2023-12-01",
    category: "Non-Vegetarian",
    freeDelivery: false,
  },
  {
    name: "Classic Cheese",
    description: "Simple and cheesy with a golden crust.",
    image: "../assets/pizza9.jpg",
    price: 9.99,
    dateOfLaunch: "2023-12-15",
    category: "Vegetarian",
    freeDelivery: true,
  },
  {
    name: "Garden Fresh",
    description: "Loaded with fresh veggies and herbs.",
    image: "../assets/pizza10.jpg",
    price: 12.19,
    dateOfLaunch: "2024-01-01",
    category: "Vegetarian",
    freeDelivery: false,
  },
];

window.pizzas = pizzas;
